name: Teste API python

on:
  push:
    branches: ['*']

jobs:
  Python:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12", "3.11", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Iniciando Flask
      run: |
        flask --app main.py run

